/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/apps/': RouteRecordInfo<
      '/apps/',
      '/apps',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/apps/docker': RouteRecordInfo<
      '/apps/docker',
      '/apps/docker',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth': RouteRecordInfo<
      '/auth',
      '/auth',
      Record<never, never>,
      Record<never, never>,
      | '/auth/'
      | '/auth/code-login'
      | '/auth/forgot-password'
      | '/auth/oauth2-callback'
      | '/auth/otp'
      | '/auth/sign-in'
      | '/auth/sign-in-2'
      | '/auth/sign-up'
    >,
    '/auth/': RouteRecordInfo<
      '/auth/',
      '/auth',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/code-login': RouteRecordInfo<
      '/auth/code-login',
      '/auth/code-login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/forgot-password': RouteRecordInfo<
      '/auth/forgot-password',
      '/auth/forgot-password',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/oauth2-callback': RouteRecordInfo<
      '/auth/oauth2-callback',
      '/auth/oauth2-callback',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/otp': RouteRecordInfo<
      '/auth/otp',
      '/auth/otp',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/sign-in': RouteRecordInfo<
      '/auth/sign-in',
      '/auth/sign-in',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/sign-in-2': RouteRecordInfo<
      '/auth/sign-in-2',
      '/auth/sign-in-2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/sign-up': RouteRecordInfo<
      '/auth/sign-up',
      '/auth/sign-up',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/': RouteRecordInfo<
      '/dashboard/',
      '/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/academy': RouteRecordInfo<
      '/dashboard/academy',
      '/dashboard/academy',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/apps/ai-chat': RouteRecordInfo<
      '/dashboard/apps/ai-chat',
      '/dashboard/apps/ai-chat',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/apps/ai-image-generator': RouteRecordInfo<
      '/dashboard/apps/ai-image-generator',
      '/dashboard/apps/ai-image-generator',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/apps/api-keys': RouteRecordInfo<
      '/dashboard/apps/api-keys',
      '/dashboard/apps/api-keys',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/apps/calendar': RouteRecordInfo<
      '/dashboard/apps/calendar',
      '/dashboard/apps/calendar',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/apps/chat': RouteRecordInfo<
      '/dashboard/apps/chat',
      '/dashboard/apps/chat',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/apps/file-manager': RouteRecordInfo<
      '/dashboard/apps/file-manager',
      '/dashboard/apps/file-manager',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/apps/kanban': RouteRecordInfo<
      '/dashboard/apps/kanban',
      '/dashboard/apps/kanban',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/apps/mail': RouteRecordInfo<
      '/dashboard/apps/mail',
      '/dashboard/apps/mail',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/apps/notes': RouteRecordInfo<
      '/dashboard/apps/notes',
      '/dashboard/apps/notes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/apps/pos-system': RouteRecordInfo<
      '/dashboard/apps/pos-system',
      '/dashboard/apps/pos-system',
      Record<never, never>,
      Record<never, never>,
      | '/dashboard/apps/pos-system/tables'
    >,
    '/dashboard/apps/pos-system/tables': RouteRecordInfo<
      '/dashboard/apps/pos-system/tables',
      '/dashboard/apps/pos-system/tables',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/apps/todo-list-app': RouteRecordInfo<
      '/dashboard/apps/todo-list-app',
      '/dashboard/apps/todo-list-app',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/crm': RouteRecordInfo<
      '/dashboard/crm',
      '/dashboard/crm',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/crypto': RouteRecordInfo<
      '/dashboard/crypto',
      '/dashboard/crypto',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/ecommerce': RouteRecordInfo<
      '/dashboard/ecommerce',
      '/dashboard/ecommerce',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/empty-states/01': RouteRecordInfo<
      '/dashboard/empty-states/01',
      '/dashboard/empty-states/01',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/empty-states/02': RouteRecordInfo<
      '/dashboard/empty-states/02',
      '/dashboard/empty-states/02',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/empty-states/03': RouteRecordInfo<
      '/dashboard/empty-states/03',
      '/dashboard/empty-states/03',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/empty-states/coming-soon': RouteRecordInfo<
      '/dashboard/empty-states/coming-soon',
      '/dashboard/empty-states/coming-soon',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/file-manager': RouteRecordInfo<
      '/dashboard/file-manager',
      '/dashboard/file-manager',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/finance': RouteRecordInfo<
      '/dashboard/finance',
      '/dashboard/finance',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/hospital-management': RouteRecordInfo<
      '/dashboard/hospital-management',
      '/dashboard/hospital-management',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/hotel': RouteRecordInfo<
      '/dashboard/hotel',
      '/dashboard/hotel',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/logistics': RouteRecordInfo<
      '/dashboard/logistics',
      '/dashboard/logistics',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/onboarding-flow': RouteRecordInfo<
      '/dashboard/onboarding-flow',
      '/dashboard/onboarding-flow',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/orders/': RouteRecordInfo<
      '/dashboard/orders/',
      '/dashboard/orders',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/orders/[id]': RouteRecordInfo<
      '/dashboard/orders/[id]',
      '/dashboard/orders/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/dashboard/orders/detail': RouteRecordInfo<
      '/dashboard/orders/detail',
      '/dashboard/orders/detail',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/pricing/column': RouteRecordInfo<
      '/dashboard/pricing/column',
      '/dashboard/pricing/column',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/pricing/single': RouteRecordInfo<
      '/dashboard/pricing/single',
      '/dashboard/pricing/single',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/pricing/table': RouteRecordInfo<
      '/dashboard/pricing/table',
      '/dashboard/pricing/table',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/products/': RouteRecordInfo<
      '/dashboard/products/',
      '/dashboard/products',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/products/[id]': RouteRecordInfo<
      '/dashboard/products/[id]',
      '/dashboard/products/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/dashboard/products/create': RouteRecordInfo<
      '/dashboard/products/create',
      '/dashboard/products/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/profile': RouteRecordInfo<
      '/dashboard/profile',
      '/dashboard/profile',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/project-management': RouteRecordInfo<
      '/dashboard/project-management',
      '/dashboard/project-management',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/sales': RouteRecordInfo<
      '/dashboard/sales',
      '/dashboard/sales',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/system': RouteRecordInfo<
      '/dashboard/system',
      '/dashboard/system',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/website-analytics': RouteRecordInfo<
      '/dashboard/website-analytics',
      '/dashboard/website-analytics',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/errors': RouteRecordInfo<
      '/errors',
      '/errors',
      Record<never, never>,
      Record<never, never>,
      | '/errors/'
      | '/errors/401'
      | '/errors/403'
      | '/errors/404'
      | '/errors/500'
      | '/errors/503'
    >,
    '/errors/': RouteRecordInfo<
      '/errors/',
      '/errors',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/errors/401': RouteRecordInfo<
      '/errors/401',
      '/errors/401',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/errors/403': RouteRecordInfo<
      '/errors/403',
      '/errors/403',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/errors/404': RouteRecordInfo<
      '/errors/404',
      '/errors/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/errors/500': RouteRecordInfo<
      '/errors/500',
      '/errors/500',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/errors/503': RouteRecordInfo<
      '/errors/503',
      '/errors/503',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/help-center': RouteRecordInfo<
      '/help-center',
      '/help-center',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/plugin/': RouteRecordInfo<
      '/plugin/',
      '/plugin',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/plugin/[name]': RouteRecordInfo<
      '/plugin/[name]',
      '/plugin/:name',
      { name: ParamValue<true> },
      { name: ParamValue<false> },
      | never
    >,
    '/plugin/theme/': RouteRecordInfo<
      '/plugin/theme/',
      '/plugin/theme',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/plugin/theme/tweak': RouteRecordInfo<
      '/plugin/theme/tweak',
      '/plugin/theme/tweak',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/profile/': RouteRecordInfo<
      '/profile/',
      '/profile',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/scene/automation': RouteRecordInfo<
      '/scene/automation',
      '/scene/automation',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/backup-restore': RouteRecordInfo<
      '/settings/backup-restore',
      '/settings/backup-restore',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/notifications': RouteRecordInfo<
      '/settings/notifications',
      '/settings/notifications',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/upgrade': RouteRecordInfo<
      '/settings/upgrade',
      '/settings/upgrade',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/users/': RouteRecordInfo<
      '/users/',
      '/users',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
    }
    'src/pages/apps/index.vue': {
      routes:
        | '/apps/'
      views:
        | never
    }
    'src/pages/apps/docker.vue': {
      routes:
        | '/apps/docker'
      views:
        | never
    }
    'src/pages/auth.vue': {
      routes:
        | '/auth'
        | '/auth/'
        | '/auth/code-login'
        | '/auth/forgot-password'
        | '/auth/oauth2-callback'
        | '/auth/otp'
        | '/auth/sign-in'
        | '/auth/sign-in-2'
        | '/auth/sign-up'
      views:
        | 'default'
    }
    'src/pages/auth/index.vue': {
      routes:
        | '/auth/'
      views:
        | never
    }
    'src/pages/auth/code-login.vue': {
      routes:
        | '/auth/code-login'
      views:
        | never
    }
    'src/pages/auth/forgot-password.vue': {
      routes:
        | '/auth/forgot-password'
      views:
        | never
    }
    'src/pages/auth/oauth2-callback.vue': {
      routes:
        | '/auth/oauth2-callback'
      views:
        | never
    }
    'src/pages/auth/otp.vue': {
      routes:
        | '/auth/otp'
      views:
        | never
    }
    'src/pages/auth/sign-in.vue': {
      routes:
        | '/auth/sign-in'
      views:
        | never
    }
    'src/pages/auth/sign-in-2.vue': {
      routes:
        | '/auth/sign-in-2'
      views:
        | never
    }
    'src/pages/auth/sign-up.vue': {
      routes:
        | '/auth/sign-up'
      views:
        | never
    }
    'src/pages/dashboard/index.vue': {
      routes:
        | '/dashboard/'
      views:
        | never
    }
    'src/pages/dashboard/academy.vue': {
      routes:
        | '/dashboard/academy'
      views:
        | never
    }
    'src/pages/dashboard/apps/ai-chat.vue': {
      routes:
        | '/dashboard/apps/ai-chat'
      views:
        | never
    }
    'src/pages/dashboard/apps/ai-image-generator.vue': {
      routes:
        | '/dashboard/apps/ai-image-generator'
      views:
        | never
    }
    'src/pages/dashboard/apps/api-keys.vue': {
      routes:
        | '/dashboard/apps/api-keys'
      views:
        | never
    }
    'src/pages/dashboard/apps/calendar.vue': {
      routes:
        | '/dashboard/apps/calendar'
      views:
        | never
    }
    'src/pages/dashboard/apps/chat.vue': {
      routes:
        | '/dashboard/apps/chat'
      views:
        | never
    }
    'src/pages/dashboard/apps/file-manager.vue': {
      routes:
        | '/dashboard/apps/file-manager'
      views:
        | never
    }
    'src/pages/dashboard/apps/kanban.vue': {
      routes:
        | '/dashboard/apps/kanban'
      views:
        | never
    }
    'src/pages/dashboard/apps/mail.vue': {
      routes:
        | '/dashboard/apps/mail'
      views:
        | never
    }
    'src/pages/dashboard/apps/notes.vue': {
      routes:
        | '/dashboard/apps/notes'
      views:
        | never
    }
    'src/pages/dashboard/apps/pos-system.vue': {
      routes:
        | '/dashboard/apps/pos-system'
        | '/dashboard/apps/pos-system/tables'
      views:
        | 'default'
    }
    'src/pages/dashboard/apps/pos-system/tables.vue': {
      routes:
        | '/dashboard/apps/pos-system/tables'
      views:
        | never
    }
    'src/pages/dashboard/apps/todo-list-app.vue': {
      routes:
        | '/dashboard/apps/todo-list-app'
      views:
        | never
    }
    'src/pages/dashboard/crm.vue': {
      routes:
        | '/dashboard/crm'
      views:
        | never
    }
    'src/pages/dashboard/crypto.vue': {
      routes:
        | '/dashboard/crypto'
      views:
        | never
    }
    'src/pages/dashboard/ecommerce.vue': {
      routes:
        | '/dashboard/ecommerce'
      views:
        | never
    }
    'src/pages/dashboard/empty-states/01.vue': {
      routes:
        | '/dashboard/empty-states/01'
      views:
        | never
    }
    'src/pages/dashboard/empty-states/02.vue': {
      routes:
        | '/dashboard/empty-states/02'
      views:
        | never
    }
    'src/pages/dashboard/empty-states/03.vue': {
      routes:
        | '/dashboard/empty-states/03'
      views:
        | never
    }
    'src/pages/dashboard/empty-states/coming-soon.vue': {
      routes:
        | '/dashboard/empty-states/coming-soon'
      views:
        | never
    }
    'src/pages/dashboard/file-manager.vue': {
      routes:
        | '/dashboard/file-manager'
      views:
        | never
    }
    'src/pages/dashboard/finance.vue': {
      routes:
        | '/dashboard/finance'
      views:
        | never
    }
    'src/pages/dashboard/hospital-management.vue': {
      routes:
        | '/dashboard/hospital-management'
      views:
        | never
    }
    'src/pages/dashboard/hotel.vue': {
      routes:
        | '/dashboard/hotel'
      views:
        | never
    }
    'src/pages/dashboard/logistics.vue': {
      routes:
        | '/dashboard/logistics'
      views:
        | never
    }
    'src/pages/dashboard/onboarding-flow.vue': {
      routes:
        | '/dashboard/onboarding-flow'
      views:
        | never
    }
    'src/pages/dashboard/orders/index.vue': {
      routes:
        | '/dashboard/orders/'
      views:
        | never
    }
    'src/pages/dashboard/orders/[id].vue': {
      routes:
        | '/dashboard/orders/[id]'
      views:
        | never
    }
    'src/pages/dashboard/orders/detail.vue': {
      routes:
        | '/dashboard/orders/detail'
      views:
        | never
    }
    'src/pages/dashboard/pricing/column.vue': {
      routes:
        | '/dashboard/pricing/column'
      views:
        | never
    }
    'src/pages/dashboard/pricing/single.vue': {
      routes:
        | '/dashboard/pricing/single'
      views:
        | never
    }
    'src/pages/dashboard/pricing/table.vue': {
      routes:
        | '/dashboard/pricing/table'
      views:
        | never
    }
    'src/pages/dashboard/products/index.vue': {
      routes:
        | '/dashboard/products/'
      views:
        | never
    }
    'src/pages/dashboard/products/[id].vue': {
      routes:
        | '/dashboard/products/[id]'
      views:
        | never
    }
    'src/pages/dashboard/products/create.vue': {
      routes:
        | '/dashboard/products/create'
      views:
        | never
    }
    'src/pages/dashboard/profile.vue': {
      routes:
        | '/dashboard/profile'
      views:
        | never
    }
    'src/pages/dashboard/project-management.vue': {
      routes:
        | '/dashboard/project-management'
      views:
        | never
    }
    'src/pages/dashboard/sales.vue': {
      routes:
        | '/dashboard/sales'
      views:
        | never
    }
    'src/pages/dashboard/system.vue': {
      routes:
        | '/dashboard/system'
      views:
        | never
    }
    'src/pages/dashboard/website-analytics.vue': {
      routes:
        | '/dashboard/website-analytics'
      views:
        | never
    }
    'src/pages/errors.vue': {
      routes:
        | '/errors'
        | '/errors/'
        | '/errors/401'
        | '/errors/403'
        | '/errors/404'
        | '/errors/500'
        | '/errors/503'
      views:
        | 'default'
    }
    'src/pages/errors/index.vue': {
      routes:
        | '/errors/'
      views:
        | never
    }
    'src/pages/errors/401.vue': {
      routes:
        | '/errors/401'
      views:
        | never
    }
    'src/pages/errors/403.vue': {
      routes:
        | '/errors/403'
      views:
        | never
    }
    'src/pages/errors/404.vue': {
      routes:
        | '/errors/404'
      views:
        | never
    }
    'src/pages/errors/500.vue': {
      routes:
        | '/errors/500'
      views:
        | never
    }
    'src/pages/errors/503.vue': {
      routes:
        | '/errors/503'
      views:
        | never
    }
    'src/pages/help-center.vue': {
      routes:
        | '/help-center'
      views:
        | never
    }
    'src/pages/plugin/index.vue': {
      routes:
        | '/plugin/'
      views:
        | never
    }
    'src/pages/plugin/[name].vue': {
      routes:
        | '/plugin/[name]'
      views:
        | never
    }
    'src/pages/plugin/theme/index.vue': {
      routes:
        | '/plugin/theme/'
      views:
        | never
    }
    'src/pages/plugin/theme/tweak.vue': {
      routes:
        | '/plugin/theme/tweak'
      views:
        | never
    }
    'src/pages/profile/index.vue': {
      routes:
        | '/profile/'
      views:
        | never
    }
    'src/pages/scene/automation.vue': {
      routes:
        | '/scene/automation'
      views:
        | never
    }
    'src/pages/settings/backup-restore.vue': {
      routes:
        | '/settings/backup-restore'
      views:
        | never
    }
    'src/pages/settings/notifications.vue': {
      routes:
        | '/settings/notifications'
      views:
        | never
    }
    'src/pages/settings/upgrade.vue': {
      routes:
        | '/settings/upgrade'
      views:
        | never
    }
    'src/pages/users/index.vue': {
      routes:
        | '/users/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
