name: Release changelog

on:
  push:
    tags:
      - v*

jobs:
  changelog:
    if: github.repository_owner == 'muthur-command'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          ref: mc_fd

      - uses: rhysd/changelog-from-release/action@78b335bb7d059f35ad04c5428d50711726feee50 # v3
        with:
          file: CHANGELOG.md
          pull_request: true
          commit_summary_template: 'Update the changelog for %s'
          args: -c
          github_token: ${{ secrets.GH_TOKEN }}
